### ISSUE TITLE
Implement category votes

### ISSUE THREAD

**Issue by everson-ever** [Sintrop/app-main-react#7]
# Description

Implementar votação de categorias! No sistema da Sintrop, um usuário pode votar em uma categorias do sistema utilizando SAC Tokens!

Por exemplo:

Supondo que o usuário Emanuel possui `1000 SAC tokens` e deseja votar na categoria de `ID = 1` e na hora de votar, ele envia 50 SAC tokens pra essa categoria. 
 
Após a votação teremos que Emanuel possui apenas 950 SAC tokens, pois 50 tokens ele enviou pra a categoria de ID 1

O ponto interessante é que Emanuel pode retirar seu voto da categoria que ele votou, ou seja, os tokens voltam pra a carteira de Emanuel, ficando assim com 1000 SAC tokens de novo.

<br>

## Configurando votação

- A VOTAÇÃO JÁ ESTÁ CONFIGURADA NO DEPLOY

<br>

### Pegando owner via console (O owner possui tokens)

- Entre no console `truffle console`  (certifique-se de ter rodado `truffle migrate` antes)
- Rode o comando a seguir `let accounts = await web3.eth.getAccounts()`
- Chame a variável `accounts`
- O primeiro endereço da lista é o owner

<br>

### Votando em uma categoria (exemplo no console `truffle console`)

Primeiro vou criar uma categoria fake para que possamos votar nela: 

```
var categoryContract = await CategoryContract.deployed()
await categoryContract.addCategory('name', 'description', 'aa', 'bb', 'cc', 'dd', 'ee')
```

Votando na categoria criada (ID 1)

```
await categoryContract.vote(1, "10000000000000000000")
```

Checando quanto votos uma categoria possui

```
const votes = await categoryContract.votes(1)
votes.toString()
```

Quantos tokens o usuário votou em certa categoria

```
const voted = await category.voted('0xB7c7e4e09f6629BD0030566fDE5F94E820784106', 1)
voted.toString()
```

# How to

- [ ] Deve ser possível votar em uma categoria
- [ ] Deve ser possível remover voto de uma categoria

# Acceptance

- [ ] A ação de votar e remover voto deve está implementada e funcionando

**Comment by rav-andre** [comment]
@emanoeledevapps @everson-ever em que pé ficamos com essa parte?? Ainda não está totalmente funcional certo?
Está faltando alguma coisa do back-end para implementar a função de unvote?
